name: Build and deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Install dependencies
        run: npm ci
      - name: Build dependencies
        run: npm run build
      - name: Generate
        run: npm run generate
      - name: Archive production artifact
        uses: actions/upload-artifact@main
        with:
          name: dist
          path: dist
          if-no-files-found: error
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Download artifact
        uses: actions/download-artifact@main
        with:
          name: dist
          path: ./
      - name: Synct files to hosting
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp.danielqueiroz.com
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.PASSWORD }}
